### ISSUE TITLE
Er zijn nu 7 errors

### ISSUE THREAD

**Issue by Theo-denBlanken** [HugovanderGeest/FRO#2]
bij validatie. De werking is wel in orde

**Comment by HugovanderGeest** [comment]
Besten Theo,

U heeft mijn werk na gekeken en heeft per mail laten weten dat ik inderdaad nog 7 Error had,  nu heb ik inderdaad niet op de error gelet en is dat zeer slecht van mij,

Toch vraag ik u om nog 1 keer te kijken naar de opdracht. Heb hem verbeterd. 😉
http://25383.hosts1.ma-cloud.nl/FRO/formulieren/

Met vriendelijke groet,
Hugo van der Geest


Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

Van: Theo den Blanken<mailto:notifications@github.com>
Verzonden: woensdag 27 november 2019 23:20
Aan: HugovanderGeest/FRO<mailto:FRO@noreply.github.com>
CC: Subscribed<mailto:subscribed@noreply.github.com>
Onderwerp: [HugovanderGeest/FRO] Er zijn nu 7 errors (#2)


bij validatie. De werking is wel in orde

**Comment by HugovanderGeest** [comment]
errosr verholopen
